### ISSUE TITLE
Additional Occlusion Modes

### ISSUE THREAD

**Issue by ianm32** [cdverrett94/FVTT-overhead-tile-fade-for-all-tokens#5]
Would it be possible to have this work with the other tile occlusion modes in Foundry as well, such as Radial?  My use case is that I have a large overhanging roof tile that I want to be mostly visible, but enemy tokens beneath it that players would have line of sight to.

**Comment by cdverrett94** [comment]
So I took a look at doing this today. Doing it for Radial would technically be possible, but not in a way that makes sense or desirable. I'll keep looking to see if I just missed something. Fading the entire roof tile based on vision of a token underneath it is definitely possible. If you're looking for the roof to still be visible except for the area the token occupies, I think the Better Roofs module would better serve you.

**Comment by cdverrett94** [comment]
So after posting this, I actually had an idea. So doing this with Radial tiles will be possible as well.

**Comment by ianm32** [comment]
That would be cool!  What I had in mind was the radial occlusion, but visible to everyone who can see the token instead of only the owner.  I wasn't able to find a setting in Better Roofs that did what I had in mind.  If you decide to implement this, I think it would be cool!

**Comment by cdverrett94** [comment]
Alright new version released. roofs only really work for tokens outside of a building because of how core Foundry determines what tokens are visible.
