### ISSUE TITLE
[Feature Request] - Radial reveal mode

### ISSUE THREAD

**Issue by Co0nmz** [cdverrett94/FVTT-overhead-tile-fade-for-all-tokens#8]
Please add an option to reveal only the tokens surroundings instead of fading the whole overhead tile. (e.g. revealing a 10 ft circle around the token)
Please make the radius of the revealed circle a global option.

**Comment by cdverrett94** [comment]
Sorry, I never got an email when this issue was created. If you choose the radial occlusion mode, that should already be happening. As far as the radius to reveal, that's a core setting that I don't really want to mess with overriding.
